name: Deploy Laravel

on:
  push:
    branches:
      - main # adjust if you deploy from another branch

jobs:
  deploy-laravel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Laravel to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/laravel
            git pull origin main
            sudo docker-compose build laravel
            sudo docker-compose up -d laravel
            # Run migrations after deploy
            sudo docker exec laravel-app php artisan migrate --force
